version: "3"

services:

  backend:
    build:
      context: ./backend
      args:
        - API_TOKEN=${API_TOKEN}
        - RECIPIENTS=${RECIPIENTS}
    environment:
      - API_TOKEN=${API_TOKEN}
      - RECIPIENTS=${RECIPIENTS}
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    networks:
      - backnet
      - frontnet

  email_parser:
    build:
      context: ./email_parser
      args:
        - API_TOKEN=${API_TOKEN}
        - RECIPIENTS=${RECIPIENTS}
        - EMAIL_HOST=${EMAIL_HOST}
        - EMAIL_PORT=${EMAIL_PORT}
        - EMAIL_DOMAIN=${EMAIL_DOMAIN}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - GREETING_TEXT=${GREETING_TEXT}
    environment:
        - API_TOKEN=${API_TOKEN}
        - RECIPIENTS=${RECIPIENTS}
        - EMAIL_HOST=${EMAIL_HOST}
        - EMAIL_PORT=${EMAIL_PORT}
        - EMAIL_DOMAIN=${EMAIL_DOMAIN}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - GREETING_TEXT=${GREETING_TEXT}
    volumes:
      - ./email_parser:/app
    ports:
      - "8081:8081"
    networks:
      - backnet
      - frontnet

  chatbot:
    build:
      context: ./chatbot
      args:
        - API_TOKEN=${API_TOKEN}
        - RECIPIENTS=${RECIPIENTS}
        - HASHTAGS=${HASHTAGS}
    environment:
      - API_TOKEN=${API_TOKEN}
      - RECIPIENTS=${RECIPIENTS}
      - HASHTAGS=${HASHTAGS}
    volumes:
      - ./chatbot:/chatbot

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - frontnet

networks:
  backnet:
  frontnet:
